### ISSUE TITLE
list version

### ISSUE THREAD

**Issue by Mayy9999** [Cleoche/obsidian-callout-integrator#15]
I really appreciate your work. I'm just wondering if it would be possible to have a list version (`-` instead of `>`) of this plugin?

**Comment by Cleoche** [comment]
Actually, Obsidian has built-in functionality for this! Go to Settings -> hotkeys and search for "toggle bullet list", and you'll be good to go! Obsidian also has a toggle blockquote function, but I made this plugin as it doesn't supported nested blockquotes like you need for nested callouts. Hope this helps!

**Comment by Mayy9999** [comment]
Thank you so much for your kindly help!
