### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by berot3** [Cleoche/obsidian-callout-integrator#8]
Hi!

Just a question, but I just was wondering if it would be possible to automatically run/trigger this plugin when I do a callout and there is text directly under it without `>`. Or is this something that's simply not possible in obsidian?

**Comment by Cleoche** [comment]
It absolutely would be possible, but it would cause issues if you tried to go back and add a callout earlier in your note. If this turns out to be a popular request, I will consider it in the future.
